### PR TITLE
search UI implemented

### PR DESCRIPTION
**Pull request by sarthak77**
screenshot from 2019-03-06 16-07-30
screenshot from 2019-03-06 16-07-39
 Changes made to UI
Pull request #13

### CODE REVIEW

**Comment by jaskirat2000** [comment]
@iamgrawal

**Comment by sarthak77** [comment]
@iamgrawal can you review it as it will help to improve upon the future designs relating to the frontend

**Comment by sarthak77** [comment]
Is the pr merged? @jaskirat2000 @iamgrawal

**Comment by iamgrawal** [comment]
Hey @sarthak77, you are merging it in master. But since we would be starting working on version 2. so this pull request can't be merged. It would be great if you can make a pull request for the v2 branch. Also, It would be great if you can address the issue you are solving in this pr.

**Comment by iamgrawal** [comment]
I am closing this pull request since in V2 you need to create everything from scratch in Vue.js

**Pull request closed without merging**
