### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by sarthak77**
screenshot from 2019-03-07 02-30-55

Pull request #14

### CODE REVIEW

**Comment by sarthak77** [comment]
@jaskirat2000 is the pr merged or something more required?

**Comment by sarthak77** [comment]
@jaskirat2000 ??

**Comment by iamgrawal** [comment]
Hey @sarthak77, you are merging it in master. But since we would be starting working on version 2. so this pull request can't be merged. It would be great if you can make a pull request for the v2 branch. Also, It would be great if you can address the issue you are solving in this pr.

**Comment by iamgrawal** [comment]
I am closing this pull request, since in V2 you need to create everything from scratch in Vue.js

**Pull request closed without merging**
